name: DingTalk Release Notify

on:
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  release-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: visiky/dingtalk-release-notify@test
        with:
          DING_TALK_TOKEN: ${{ secrets.DING_TALK_TOKEN}}
          notify_title: '🎉 Resume release {release_tag} 🎉'
          notify_body: '测试 G2'
          notify_footer: ''
          at_all: false
